import os
from pymongo import MongoClient
from datetime import datetime

def save_guide_to_db(guide_data):
    """
    Connects to MongoDB and saves or updates a guide.
    """
    MONGO_URI = os.getenv("MONGO_URI")
    if not MONGO_URI:
        print("MONGO_URI not found.")
        return

    try:
        client = MongoClient(MONGO_URI)
        db = client.followme_db
    except Exception as e:
        print(f"DB connection failed: {e}")
        return

    # Use update_one with upsert=True to either insert a new guide
    # or update an existing one for the same target URL.
    db.analyzed_guides.update_one(
        {'url': guide_data['url']},
        {'$set': guide_data},
        upsert=True
    )
    print(f"Guide for {guide_data['url']} saved to database.")


if __name__ == '__main__':
    # Example usage
    from dotenv import load_dotenv
    # Load .env from the server directory to get the MONGO_URI
    dotenv_path = os.path.join(os.path.dirname(__file__), '../server/.env')
    load_dotenv(dotenv_path=dotenv_path)

    # This is a placeholder for a guide generated by the path_finder
    example_guide = {
        "url": "http://127.0.0.1:5500/example/page1.html",
        "steps": [
            {"selector": "a.button-next", "title": "Step 1", "description": "Click this button to proceed."},
            {"selector": "#submit-form", "title": "Step 2", "description": "Then, submit the form here."}
        ],
        "analyzed_at": datetime.utcnow()
    }
    save_guide_to_db(example_guide)
